CLASS zbp_lib_libro_06 DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zi_libro_06.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_lib_libro_06 IMPLEMENTATION.
ENDCLASS.
